version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: edge.vidi26sept.integrations:Test
  packages:
  - name: EdgeVidi26Sept
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
- serviceName: edge.vidi26sept.integrations:T1
  packages:
  - name: EdgeVidi26Sept
    version: "1.0"
- serviceName: pub.string:toUpper
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
- serviceName: edge.vidi26sept.integrations:T3
  packages:
  - name: EdgeVidi26Sept
    version: "1.0"
packages:
- name: EdgeVidi26Sept
  gitServerName: vidi26Sep
  gitUrl: https://github.com/vijetadixit/EdgeVidi26Sept
  gitUsername: vijetadixit
  gitToken: edge.scaffolding.EdgeVidi26Sept.vidi26Sep.gitToken
  gitBranch: main
